version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    restart: always
    network_mode: "host"
  app:
    image: r1mok/pet-schedule
    depends_on:
      - db
    ports:
      - 8080:8080
    network_mode: "host"